# -*- coding: utf-8 -*-
"""Week_05_11_02_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wMLCuZu4QyVdSvMuPM2Vzu3WKnLjSUA7
"""

!pip install diffusers transformers accelerate torch

import torch
from diffusers import StableDiffusionInstructPix2PixPipeline, EulerAncestralDiscreteScheduler
from PIL import Image
import matplotlib.pyplot as plt
import os


INPUT_IMAGE = "/content/WhatsApp Image 2026-01-08 at 13.21.25.jpeg"  # Ensure this file exists in the folder

# List of prompts to generate
PROMPT_LIST = [
    "change the background to a snowy mountain peak",

"make me stand in front of the Eiffel Tower",

"put me in a library full of old books",

"make the background look like an underwater coral reef",

"change the setting to a busy Times Square at night",
    "Make me ride a superbike"

]

IMAGE_STABILITY = 2
TEXT_STRENGTH = 10.0


device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

print(f"--- Multi-Prompt Generator (Running on {device}) ---")

# Load Model
model_id = "timbrooks/instruct-pix2pix"
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
    model_id, torch_dtype=dtype, safety_checker=None
).to(device)
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)

# Load Input Image
if not os.path.exists(INPUT_IMAGE):
    print(f"❌ Error: Could not find '{INPUT_IMAGE}'.")
    exit()

original_image = Image.open(INPUT_IMAGE).convert("RGB")
original_image = original_image.resize((512, 512))


print(f"Loaded image. Processing {len(PROMPT_LIST)} prompts...\n")

for i, prompt in enumerate(PROMPT_LIST):
    print(f"🎨 Generating {i+1}/{len(PROMPT_LIST)}: '{prompt}'...")

    # Generate
    with torch.no_grad():
        result = pipe(
            prompt,
            image=original_image,
            num_inference_steps=40,
            image_guidance_scale=IMAGE_STABILITY,
            guidance_scale=TEXT_STRENGTH
        ).images[0]

    # Save locally
    filename = f"output_{i}_{prompt[:10].replace(' ', '_')}.png"
    result.save(filename)


    plt.figure(figsize=(12, 6))

    # Left: Original
    plt.subplot(1, 2, 1)
    plt.imshow(original_image)
    plt.title("Original")
    plt.axis("off")

    # Right: Generated
    plt.subplot(1, 2, 2)
    plt.imshow(result)
    plt.title(f"Result: {prompt}")
    plt.axis("off")

    plt.show()
    print(f"✅ Saved to {filename}\n" + "-"*40)

print("All done!")